### ISSUE TITLE
Set up Kanban Board

### ISSUE THREAD

**Issue by Arch-Noize** [sadaf-Daneshgar/recipe_app#12]
We are a team of two people, and we've divided the work evenly from our point of view. Here's the link to our project:
https://github.com/sadaf-Daneshgar/recipe_app/projects/1

@sadaf-Daneshgar  is designated as Team Member # 2 ( As seen in https://github.com/sadaf-Daneshgar/recipe_app/issues/5), @Arch-Noize is designated as Team Member # 1 (as seen in https://github.com/sadaf-Daneshgar/recipe_app/issues/4), and both are divided to work on the Group Tasks (as seen in https://github.com/sadaf-Daneshgar/recipe_app/issues/10)

**Comment by Abenezer-Tilahun** [comment]
Hi @Arch-Noize @sadaf-Daneshgar 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ Correctly Set up RoR group project: set up your Kanban board.
✔️ Correctly organization and description about the number of people in group.


## Optional suggestions 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
